/**
 * Netscape cookies.txt parser.
 *
 * Format (tab-separated):
 *   domain  includeSubdomains  path  secure  expires  name  value
 *
 * Lines starting with `#` are comments and ignored, EXCEPT the `#HttpOnly_`
 * prefix some exporters use to mark HttpOnly cookies.
 */

import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import type { NetscapeCookie } from './types'

const HTTPONLY_PREFIX = '#HttpOnly_'

function parseLine(line: string): NetscapeCookie | null {
  let raw = line
  let httpOnly = false

  if (raw.startsWith(HTTPONLY_PREFIX)) {
    httpOnly = true
    raw = raw.slice(HTTPONLY_PREFIX.length)
  } else if (raw.startsWith('#')) {
    return null // comment
  }

  const trimmed = raw.trim()
  if (!trimmed) return null

  // Netscape format is tab-separated; fall back to splitting on runs of
  // whitespace for files that got reformatted.
  const parts = trimmed.includes('\t') ? trimmed.split('\t') : trimmed.split(/\s+/)
  if (parts.length < 7) return null

  const [domain, includeSub, path, secure, expires, name, ...valueParts] = parts
  const value = valueParts.join('\t') // value may itself contain tabs

  return {
    domain,
    includeSubdomains: includeSub.toUpperCase() === 'TRUE',
    path: path || '/',
    secure: secure.toUpperCase() === 'TRUE',
    expires: Number.parseInt(expires, 10) || 0,
    name,
    value,
    httpOnly
  }
}

/** Parse cookies from raw Netscape cookies.txt **text** (not a file path). */
export function parseNetscapeText(raw: string): NetscapeCookie[] {
  const cookies: NetscapeCookie[] = []
  for (const line of raw.split(/\r?\n/)) {
    const cookie = parseLine(line)
    if (cookie) cookies.push(cookie)
  }
  return cookies
}

/**
 * Parse cookies from a browser-extension JSON export, e.g. EditThisCookie /
 * "Cookie-Editor" which emit `[{ name, value, domain, path, secure,
 * httpOnly, expirationDate }, …]`. Returns `null` when the text is not such
 * an array, so callers can fall back to the Netscape parser.
 */
export function parseJsonCookies(raw: string): NetscapeCookie[] | null {
  let data: unknown
  try {
    data = JSON.parse(raw)
  } catch {
    return null
  }
  if (!Array.isArray(data)) return null

  const cookies: NetscapeCookie[] = []
  for (const item of data) {
    if (!item || typeof item !== 'object') continue
    const c = item as Record<string, unknown>
    const name = typeof c.name === 'string' ? c.name : ''
    const domain = typeof c.domain === 'string' ? c.domain : ''
    if (!name || !domain) continue
    const expires =
      typeof c.expirationDate === 'number'
        ? Math.floor(c.expirationDate)
        : typeof c.expires === 'number'
          ? Math.floor(c.expires)
          : 0
    cookies.push({
      domain,
      includeSubdomains: domain.startsWith('.'),
      path: typeof c.path === 'string' && c.path ? c.path : '/',
      secure: c.secure === true,
      expires,
      name,
      value: typeof c.value === 'string' ? c.value : '',
      httpOnly: c.httpOnly === true
    })
  }
  return cookies
}

/**
 * Parse cookies from arbitrary pasted/uploaded text — auto-detects a browser
 * JSON export vs. the Netscape tab-separated format.
 */
export function parseCookiesText(raw: string): NetscapeCookie[] {
  const json = parseJsonCookies(raw)
  if (json && json.length > 0) return json
  return parseNetscapeText(raw)
}

/** Serialize cookies back to Netscape cookies.txt content (one cookie per line). */
export function serializeNetscape(cookies: NetscapeCookie[]): string {
  const lines = [
    '# Netscape HTTP Cookie File',
    '# https://curl.haxx.se/rfc/cookie_spec.html',
    '# This file was generated by the Shopee scraper web UI.',
    ''
  ]
  for (const c of cookies) {
    const prefix = c.httpOnly ? HTTPONLY_PREFIX : ''
    lines.push(
      [
        prefix + c.domain,
        c.includeSubdomains ? 'TRUE' : 'FALSE',
        c.path || '/',
        c.secure ? 'TRUE' : 'FALSE',
        String(c.expires || 0),
        c.name,
        c.value
      ].join('\t')
    )
  }
  return lines.join('\n') + '\n'
}

/** Parse all cookies from a Netscape cookies.txt file. */
export async function parseCookiesFile(path: string): Promise<NetscapeCookie[]> {
  const abs = resolve(path)
  const raw = await readFile(abs, 'utf-8')
  return parseNetscapeText(raw)
}

/** Keep only cookies whose domain belongs to the given root (e.g. `shopee.co.id`). */
export function filterByDomain(cookies: NetscapeCookie[], rootDomain: string): NetscapeCookie[] {
  const root = rootDomain.toLowerCase()
  return cookies.filter((c) => {
    const d = c.domain.replace(/^\./, '').toLowerCase()
    return d === root || d.endsWith(`.${root}`)
  })
}
